<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>TapeDeck</AssemblyName>
    <RootNamespace>TapeDeck</RootNamespace>
    <UseWindowsTargeting>true</UseWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TapeDeck.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>
</Project>
