<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>TapeDeck</AssemblyName>
    <RootNamespace>TapeDeck.Cli</RootNamespace>
    <UseWindowsTargeting>true</UseWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TapeDeck.Core\TapeDeck.Core.csproj" />
  </ItemGroup>
</Project>
